spring.application.name=pfe-BTK
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=pfe
spring.datasource.password=pfe123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
server.address=0.0.0.0

jwt.secret=h0784zYlkCYlV1h4kXryIOlAEE81ku7xOXLzSH8pU7L

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fassatouimohamed02@gmail.com
spring.mail.password=otcv pexf winn fgsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#signateur
signature.api.url=http://localhost:8000

#File Storage / images

file.image.dir=uploads/images
file.convention.dir=uploads/conventions
file.convention.signed.dir=uploads/conventions-signed
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB